### ISSUE TITLE
Notification modals desktop (close out list) 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1716] opened 2019-04-18 16:00 UTC
Finalize market
- Update color of this string to #CED7D8 "The following market is resolved..."
- Update string to "The following market is resolved and ready to be finalized so proceeds can be claimed"
- Remove string "Please finalize this market so proceeds can be claimed"

Unsigned orders 
- Update color of this string to #EB5757 "You have unsigned orders pending..."
- Padding below "TOTAL COST (ETH)" should be 24px 
- "TOTAL COST (ETH) should be using totals component (with only the value as bold) 
- If I submit or cancel all, the modal remains open, should close 

Open orders in a resolved market
- Two small padding issues
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/6954bb94-2463-4259-8b46-1a8327e2d0fe)

Sell complete sets
- Padding issue: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/eb6b9649-cfb8-4285-8952-b4031ec0de8d)

Claim proceeds
- IF 1 market to claim from, THEN don't show the 'claim proceeds' text button on the market (just show the large button)
- IF multi markets to claim from and user taps an individual claim button, THEN disabled all other claim buttons until that transaction is confirmed (ping chwy if any questions on this one) 
- IF multi markets to claim from and user taps an claim all button, THEN disabled all other claim buttons until that transaction is confirmed (ping chwy if any questions on this one) 
- Padding issue:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d844268d-b409-4b06-bd0e-f653a8588b5a)

Claim stake and fees
- Totals issue - showing duplicate ETH and REP (See #1623) 
- Scroll issue (See #1522, still not fixed for me) 
- Padding issue:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/869decfa-5f17-41e9-bfc0-3607eeacadb0)

Orphaned orders 
- If I tap "view" it takes me to the market but triggers the "review market details" modal, ideally in this scenario the dialog should not be triggered

**Comment by andrewdamelio** [comment] 2019-07-25 18:36
@pgebheim we also need to move this into a separate epic. This story requires market lifecycles to be completely hooked up in the UI to fix/test properly.

**Comment by pgebheim** [comment] 2019-08-10 23:39
Gonna add this to Sprint 15 as well, UI still not working well enough to verify these issues.

**Comment by pgebheim** [comment] 2019-10-30 00:20
From 1485:

Modals:

- [x] -Unsigned orders
- [x] - Open orders in resolved market [modal not ready - temporary links to market page]
- [ ] - Sell complete sets
- [x] - Claim proceeds (individual market)
- [x] - Claim proceeds (multiple markets)
- [x] - Finalize markets
~- Orphaned orders [modal not ready - temporary links to market page]~
- [x] - Claim stake and fees

**Comment by pgebheim** [comment] 2019-11-05 08:05
@andrewdamelio From #1707 as part of this since its included here.

The design has different copy that works better in that situation
"You currently have a total of 5.0000 ETH to be claimed in the following markets:"

Closing #1707 as a dupe of this.

**Comment by cillianhunter0** [comment] 2020-01-07 14:15
@andrewdamelio 

I've created a new batch of tickets for notification modal styling issues: 
- 5419
- 5420
- 5421

Those tickets override the styling issues in this ticket, but they don't include any copy/functionality issues that might be in this ticket above, i'm not sure what's been done/not done from above.

**Comment by andrewdamelio** [comment] 2020-02-13 15:59
closing this issue since the notifications above appear to be working fine.

The ongoing effort for the design updates are captured in separate tickets,  below for reference
#5419
#5420
#5421

**Closed as completed by andrewdamelio** 2020-02-13 15:59 UTC
Labels: prio/1, release/v2.0
