### ISSUE TITLE
Market List: When navigating to market list from hotloaded market, market list doesn't obey the filter args

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#5751] opened 2020-01-29 01:01 UTC
It seems like it defaults to the normal filters.

**Comment by pgebheim** [comment] 2020-03-02 17:19
This may have been fixed by Andy's work on the filters.

**Comment by bconfortin** [comment] 2020-03-02 17:38
Closing because the issue is not reproducible/got fixed.

**Closed as completed by bconfortin** 2020-03-02 17:38 UTC
Labels: type/bug, release/v2.0
