### ISSUE TITLE
Repeat steps

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#340] opened 2016-02-25 18:26 UTC
![repeat steps](https://cloud.githubusercontent.com/assets/5925937/13329694/07ee8948-dbbb-11e5-8873-8780dfa2a2a2.PNG)

**Comment by tinybike** [comment] 2016-02-26 05:36
This is actually intentional.  What's happening is that if 2 transactions are created by the UI at roughly the same time, they can be assigned identical nonces.  This will cause geth to silently drop one of them from the txpool.  ethrpc checks specifically for this (a seemingly normal tx becoming null without a geth error + matching nonces) and will re-submit the transaction in that case.

That said, it probably shouldn't repeat the message to the user, since that's confusing.  I'll remove the duplicate message.

**Comment by tinybike** [comment] 2016-02-26 09:12
Added a mutual exclusion lock to the ethrpc `rawTxs` object in AugurProject/augur.js@ae577f43b8f004a13695a93b226185d746ce1e2b, which should force nonces to always be unique.  Closing since I'm no longer able to reproduce this issue.

**Closed by tinybike** 2016-02-26 09:12 UTC
Labels: bug
