### ISSUE TITLE
trade history has no scroll cut off 

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1917] opened 2019-04-26 16:53 UTC
<img width="1497" alt="Screen Shot 2019-04-26 at 9 52 31 AM" src="https://user-images.githubusercontent.com/6775839/56823545-076ba400-6809-11e9-8b12-d002ade8181d.png">

**Comment by bthaile** [comment] 2019-04-26 16:54
@Chwy5 this is easy fix, won't break anything. dev is in the code. can we fix in v1.13

**Comment by Chwy5** [comment] 2019-04-26 16:55
approved

**Comment by Chwy5** [comment] 2019-04-26 16:58
Mine is contained - what are you viewing this on?

**Comment by phoebemirman** [comment] 2019-04-26 17:01
i see it on dev and master. the market has to have lots of data in trade history

**Comment by Chwy5** [comment] 2019-04-26 17:01
mine does...doesnt look like that

**Comment by Chwy5** [comment] 2019-04-26 17:24
appears to be caused by chromes latest update....old versions show correctly

**Comment by Chwy5** [comment] 2019-04-27 23:25
closing

**Closed as completed by Chwy5** 2019-04-27 23:25 UTC
Labels: type/bug, prio/1
