### ISSUE TITLE
Update to countdown timer text styles

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1488] opened 2019-03-27 14:53 UTC
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7268%3A27729
Example here is for notifications but this change is app wide. 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/508f8d90-c707-4ad8-b13f-1cdc61805918)

Label: 
Roboto mono, all caps, 10px, #76737E

Timer: 
Roboto mono, 12px, #F1E700

**Comment by andrewdamelio** [comment] 2019-07-25 15:17
Dupe of #1568

**Closed as completed by andrewdamelio** 2019-07-25 15:17 UTC
Labels: prio/3
