### ISSUE TITLE
Shares held in market "slips" into different holding

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur#188] opened 2015-09-24 00:45 UTC
In watching http://localhost:8080/market/-2d43b0229d7f36456d1068a627b494c08b39241d6f218008c10f6836743b622a (Will 1 ETH be worthing more than 10 USD by the end of 2016?) and a little while after making a successful trade, my shares held switched from 5 of NO to 116 of YES.  

It feels like I'm somehow getting another accounts holdings.

**Comment by joeykrug** [comment] 2015-09-24 00:52
If I had to guess you've either a) jumped the time space continuum into another universe or b) cosmic rays: http://stackoverflow.com/questions/2580933/cosmic-rays-what-is-the-probability-they-will-affect-a-program

I got another accounts holdings once. but it's been a while, there used to be a "default" account, maybe it's that account's holdings?

**Comment by scottzer0** [comment] 2015-09-24 01:12
Yea.  If I attempt a trade after this "slip", I get a no-money-mo-problems error, so I'm assuming we're see a default account or something.

**Comment by tinybike** [comment] 2015-09-24 11:26
@scottzer0 does this still happen for you on http://development.augur.divshot.io/?  My guess is this was caused by using Github for versioning, which may have resulted in your build being composed of imperfectly-synched modules...

**Comment by tinybike** [comment] 2015-09-24 12:28
I have not been able to reproduce this; my guess is that it was a versioning thing and the latest dev divshot build (2f5727d02ad860948a5ae61c0a3902ca2b0dcd58) seems ok.  Closing this issue for now, but please re-open if you continue to experience this problem.

**Closed by tinybike** 2015-09-24 12:28 UTC
Labels: bug
