### ISSUE TITLE
Running client locally fails

### ISSUE THREAD

**Issue by vega113** [AugurProject/augur#227] opened 2015-12-28 12:23 UTC
Steps to reproduce:   
Install local ethereum node as described in README   
Install and run augur client as described in README   
Expected: the client can be opened in browser and runs correctly    
Actual : navigating in browser to localhost:8080 results in loading the site but gets stuck. Using the Chrome Dev Tools I can see the following log:   
```

app.js:189 connected to host: http://127.0.0.1:8545
app.js:83 using branch 1010101
app.js:932 using unlocked account: 0xaf9165bc9ed03208a4b716e415e48f4f0dff838a
app.js:91 augur.periodLength error: Object {error: "0x", message: "no response or bad input"}(anonymous function) @ app.js:91(anonymous function) @ app.js:32927(anonymous function) @ app.js:32353(anonymous function) @ app.js:5219(anonymous function) @ app.js:5431(anonymous function) @ app.js:5211(anonymous function) @ app.js:32346module.exports.parse @ app.js:32014(anonymous function) @ app.js:32126on_end @ app.js:33444on_state_change @ app.js:33394
app.js:459 Uncaught RangeError: Invalid array length(anonymous function) @ app.js:459(anonymous function) @ app.js:32927(anonymous function) @ app.js:32353(anonymous function) @ app.js:5219(anonymous function) @ app.js:5431(anonymous function) @ app.js:5211(anonymous function) @ app.js:32346module.exports.parse @ app.js:32052(anonymous function) @ app.js:32126on_end @ app.js:33444on_state_change @ app.js:33394
```

**Comment by vega113** [comment] 2015-12-28 12:24
Btw, the ethereum node fails to synchronize:
```
I1228 14:23:47.519781   24561 downloader.go:254] Synchronisation failed: hash fetching canceled (requested)
```

**Comment by tinybike** [comment] 2015-12-28 18:54
Hm.  Can you try running the augur client locally, without also running an ethereum node?  That'll help de-confound the two things so I can troubleshoot!

**Comment by vega113** [comment] 2015-12-29 06:29
Running with node down results in stuck client and the following log in browser:

    http://127.0.0.1:8545/ Failed to load resource: net::ERR_CONNECTION_REFUSED

**Comment by tinybike** [comment] 2015-12-29 09:08
That error is expected if you're not running a local node, actually.  (NB: I should probably change it to a warning.)  Is there anything else in the browser console?  It should spit out something about connecting a hosted node:
```
http://127.0.0.1:8545/ net::ERR_CONNECTION_REFUSED
connected to host: https://eth1.augur.net
connecting to hosted node
using branch 1010101
```
Do you see something like this, or it's just that error message and nothing else?

**Comment by tinybike** [comment] 2015-12-29 09:16
Also, how does the client get stuck -- do you see the starry background with the augur logo, or a plain black background, or something else?

**Comment by tinybike** [comment] 2015-12-29 09:24
Btw, are you on the augur slack?  This kind of problem is easier to troubleshoot in real-time, plus I think this issue is specific to your setup.  We have an open slack, go to http://slackinaugur.herokuapp.com/ to join (my username is @jack).

**Comment by vega113** [comment] 2015-12-29 09:38
I see the starry background

**Comment by vega113** [comment] 2015-12-29 14:48
I see something like this:
```
I1229 16:40:07.547022   28666 worker.go:294] 🔨  Mined block (#200387 / 7ee465e4). Wait 5 blocks for confirmation
I1229 16:40:07.547921   28666 worker.go:489] commit new work on block 200388 with 0 txs & 0 uncles. Took 836.569µs
I1229 16:40:07.548749   28666 worker.go:489] commit new work on block 200388 with 0 txs & 0 uncles. Took 433.187µs
eth.getBalance()
'0'
> I1229 16:41:57.902451   28666 worker.go:294] 🔨  Mined block (#200388 / d5ea0d50). Wait 5 blocks for confirmation
I1229 16:41:57.903281   28666 worker.go:489] commit new work on block 200389 with 0 txs & 0 uncles. Took 784.904µs
I1229 16:41:57.904147   28666 worker.go:489] commit new work on block 200389 with 0 txs & 0 uncles. Took 479.441µs
I1229 16:42:01.150829   28666 chain_manager.go:788] Bad block #200000 (50712a340f657d85aa77416ae1f1806a1fb39e94a5609eccdc6df4387050d697)
I1229 16:42:01.150850   28666 chain_manager.go:789] Difficulty check failed for block 6454028, 6454027
I1229 16:42:01.150912   28666 downloader.go:254] Synchronisation failed: hash fetching canceled (requested)
I1229 16:43:21.839829   28666 chain_manager.go:788] Bad block #200000 (50712a340f657d85aa77416ae1f1806a1fb39e94a5609eccdc6df4387050d697)
I1229 16:43:21.839859   28666 chain_manager.go:789] Difficulty check failed for block 6454028, 6454027
I1229 16:43:21.839921   28666 downloader.go:254] Synchronisation failed: hash fetching canceled (requested)
```

**Comment by tinybike** [comment] 2015-12-29 23:18
@vega113 are you able to connect to the hosted node now?  It turns out that one of our nodes (eth1.augur.net) went down for several hours last night.  At the moment this is the only combined ethereum/IPFS node.  I suspect your connection may have fizzled when it couldn't reach the IPFS node.  (I'll install IPFS on our other nodes and add them to the load balancer so this shouldn't be an issue going forward.)

**Comment by tinybike** [comment] 2016-01-01 03:43
I'm unable to reproduce this.  I added a separate issue for IPFS nodes / load balancing (#236); closing for now.

**Closed by tinybike** 2016-01-01 03:43 UTC

**Comment by pqdeep** [comment] 2016-01-01 13:47
Looks like he wasnt a troll
