### ISSUE TITLE
remove vertical scrolling in mobile sub nav

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1765] opened 2019-04-19 14:47 UTC
Shouldn't do this. Only horizontal scroll when required

![Kapture 2019-04-19 at 16.46.32.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/47f37092-5c34-4a41-90ea-2056d3c33635)

**Comment by JohnDanz** [comment] 2019-07-30 14:41
I was unable to reproduce that behavior on master, going to close this issue as fixed.

**Closed as completed by JohnDanz** 2019-07-30 14:41 UTC
Labels: prio/3
