### ISSUE TITLE
test trading tutorial issues

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#5797] opened 2020-01-30 15:03 UTC
order form confirmation section isn't filled out correctly
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/3dc2ad6e-c5c5-4b5c-8c26-2f453f873cc7)

Message box is pointing too low.
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/1dde61f6-a1c7-44fc-a15c-01b3a8c6b5dd)

**Comment by phoebemirman** [comment] 2020-01-30 17:50
dupe of https://github.com/AugurProject/augur/issues/5712

**Closed as completed by phoebemirman** 2020-01-30 17:50 UTC
