### ISSUE TITLE
Descriptions for claims

### ISSUE THREAD

**Issue by evand** [AugurProject/augur#128] opened 2015-07-16 03:03 UTC
Claims need a description, not just a title. Often terms need clarification if the definition isn't clear. Or we need clarification about how much of whatever is enough to "count". Or a host of other reasons that the details might not fit in a title that's short enough to put on the summary screen.

Possibly another field for "relevant info that's not part of the claim text", such as links about background info that traders might care about. I'm actually of mixed opinion on whether that's a good idea, but you definitely don't want it cluttering up the claim text and having people trying to sort out whether that info is directly relevant to judging.

**Comment by carver** [comment] 2015-07-16 21:57
Absolutely, it's unacceptable to be missing detailed descriptions by the time real money starts trading.

We've been working under the assumption that storing descriptions on chain is prohibitively expensive.  I briefly looked into using ipfs to store it a few weeks ago, but direct access to ipfs from a javascript client was unsupported at the time.

The decision from there was to wait for one of these data storage options to mature: ipfs, swarm (ethereum shared file store), or a centralized augur data store.

**Comment by evand** [comment] 2015-07-17 15:07
Why would it be expensive? Data storage on the Bitcoin blockchain is perhaps as high as a penny per kB; I don't see why Ethereum should be any worse. The available budget for market creators to pay for useful stuff is at least several dollars, for any contract worth the time to write up.

Augur could also just run their own pastebin-ish thing for now, that includes support for generating SHA hashes and looking up by hash, and just reference the hash of the claim text on-chain for now. You can always add something fancier / more robust later.

**Comment by joeykrug** [comment] 2015-07-17 17:39
An op return on Bitcoin is 40 bytes per tx, not kb, so not super cheap.  Hashing is the way to do this.

**Comment by evand** [comment] 2015-07-17 18:14
Eh, the whole blockchain is just data. It's all priced per kB. Just abuse the multsig capabilities (1-of-10, anyone?) or something. Presumably Ethereum will let you do something less dumb, but it doesn't really matter.

Hashing is a bit better, but text is small and cheap.

**Comment by joeykrug** [comment] 2015-07-17 18:50
Average transaction fee is $0.03 1024/80 = 12.8 op returns to make up 1 kb of extra data, ~38 cents.  One byte of storage on eth is 25000 gas to initialize (much cheaper to modify), to have equivalent on btc that'd be ~ 25600000 or 256 ether.  Aka not cheap and hashing is the way to go.

**Comment by niran** [comment] 2015-07-17 19:02
My understanding is that Swarm is working and accessible from geth's RPC API. If true, that could get around IPFS problems.

**Comment by joeykrug** [comment] 2015-07-17 19:08
Just looked, I don't see it anywhere. Centralized w/ hash verification until ipfs/swarm are further along is prob the way to go

**Comment by joeykrug** [comment] 2015-07-19 16:22
Found a PR for swarm. It's waiting to be merged then eth will have swarm support

**Comment by scottzer0** [comment] 2015-08-30 17:17
duplicate of #148

**Closed by scottzer0** 2015-08-30 17:17 UTC
Labels: enhancement
