### ISSUE TITLE
Click cash faucet button multiple times on new account, will never get cash b/c tx never included

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#184] opened 2015-09-21 16:39 UTC

**Comment by tinybike** [comment] 2015-09-21 17:10
To clarify, does the cash faucet not work at all for you, or does it only not work if you mash the button a bunch of times?

**Comment by joeykrug** [comment] 2015-09-21 17:29
only if mash the button

**Comment by tinybike** [comment] 2015-09-21 20:42
Hmm, maybe it'd be best to just make the button un-mashable by greying it out for 2-3 seconds after pressing -- can't think of any legit reason people would want to mash the buttons.

**Comment by joeykrug** [comment] 2015-09-21 21:50
That's just putting a bandaid on the issue. This is a manifestation of the issue where no transactions will ever go through, I don't want an account with $10k on augur to not allow me to send a transaction unless I do it via command line because there's a bug that was never fixed. Putting a ban on clicking the faucet may fix this manifestation of the issue, but it won't fix the actual issue whatever it is (it'll just make it harder to come across).

**Comment by tinybike** [comment] 2015-09-21 21:56
Are you still experiencing the no-transactions-go-thru issue (#183)?  I think this issue was fixed as of a7a76a801f63f1a7db3151e2ec47b94e75249475.  I suspect mashing the button for faucets is not a manifestation of this issue; instead, what's happening is that you're creating duplicate transactions, which are (correctly) rejected by geth.

**Comment by joeykrug** [comment] 2015-09-21 21:57
They aren't being correctly rejected, one of them should be included

**Comment by joeykrug** [comment] 2015-09-21 21:58
I waited about 10 min and tried again and still nothing on that account this morning

**Comment by tinybike** [comment] 2015-09-21 21:59
Oh, not even the first one is getting included.  I see now.  What's the account name/password, so I can try to reproduce?

**Comment by joeykrug** [comment] 2015-09-21 22:04
It seems to be working now, willitwork willitwork was the account

**Comment by tinybike** [comment] 2015-09-21 22:11
It seems ok for me too; just tried it on two new accounts and got the cash in both cases.  My guess is that you somehow lost connection to geth and that geth fallback still isn't happening correctly -- I've been intending to test that more thoroughly anyway so I'll do that.

**Comment by tinybike** [comment] 2015-09-22 12:30
It turns out the client was set up to only talk to one node, which I think has been the cause of a number of hard-to-reproduce bugs.  I fixed (and greatly simplified) the client's initial connection in 5fe69fba5601d57564d672f0ecb49c5368bbae82.  I also made some improvements to ethrpc's load balancer (AugurProject/ethrpc@bb60da12d4567037f705cfbdce9176e6949ce8e8), so that it will automatically shunt your traffic towards whichever nodes work best for you.  Seems to help:

![latency](https://cloud.githubusercontent.com/assets/2637020/10018335/b60aa670-60ea-11e5-86ab-7e98f3f59d4d.png)

Also, confirmed that basic RPC failover works.  So, *if* the underlying issue was failure to redirect RPC to geth backup nodes, the random transaction disappearance issue should be solved.  (Will leave this open for a day or two to let it stew...)

**Comment by joeykrug** [comment] 2015-09-22 17:39
So spamming cash and rep at same time, you'll end up getting cash, but I don't get my rep
![screen shot 2015-09-22 at 12 36 59 pm](https://cloud.githubusercontent.com/assets/5925937/10026356/f0b2b380-6126-11e5-9ba6-daa76638c728.png)

**Comment by joeykrug** [comment] 2015-09-22 18:38
Refreshing and logging back in and trying again works btw

**Comment by tinybike** [comment] 2015-09-22 20:58
Sorry, I forgot to push the changes up to the dev divshot -- I'll do that now.  Also, yeah, for some reason after registering, the filters aren't switching on the way they should -- although it works fine after login.  Troubleshooting...

**Comment by tinybike** [comment] 2015-09-24 11:54
Fixed in 2f5727d02ad860948a5ae61c0a3902ca2b0dcd58 / AugurProject/augur.js@309cd7d80b62fdaed6ec0a9ac625e4c8ef43d45e / AugurProject/ethrpc@e3028b9e90e9f51044279c7d8d0da2ba145b9071.  Wanted to comment on the root causes of this bug, since this may be the single most complicated bug I've encountered:

As mentioned above, some instances of this were due to random geth connection failures; this should be fixed by the load balancing / fallback improvements in AugurProject/ethrpc@bb60da12d4567037f705cfbdce9176e6949ce8e8.

In other (more frequent) cases, the problem turned out to be the client-side transaction nonce.  The accounts module had been grabbing an initial value for the nonce from `ethrpc.getTransactionCount`, and afterward simply incrementing it for each client-side transaction.  Interestingly, it turns out that geth will throw an error if the raw tx nonce is too ​low, or if you submit a duplicate transaction (i.e., same hash as another transaction which has already cleared geth's txpool).  However, raw transactions can be added successfully (i.e., without geth returning an error) if:

1. Its hash (and therefore also its nonce) is identical to another transaction in the txpool.
2. Its nonce (but not its hash) is identical to another of the sender's transactions in the txpool.

The problem is that, in both scenarios, once the first tx clears, the second tx (with the matching hash and/or nonce) will be silently removed from the pool.  Geth in fact never generates an error in either case, and in both cases, we receive no indication from geth that a transaction will be dropped until it actually is dropped.  When this happens, the `getTransaction` RPC -- which previously returned a normal-looking pending transaction -- now returns `null`.  So, ethrpc's `txNotify` now watches for this scenario (null transaction + raw client-side transaction + duplicate nonce) and re-initiates `transact`.

As far as I can tell this fixes the problem entirely; transactions never simply fail for me any longer in the client (although please double-check me on this).  I also wrote unit tests for the problematic combinations-of-transactions to hopefully keep this from recurring.  Closing (for now at least...) with great relief!

**Closed by tinybike** 2015-09-24 11:54 UTC
Labels: bug
