### ISSUE TITLE
Date picker isn't working on iOS mobile 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5053] opened 2019-12-05 13:08 UTC
When I try to select a date in the date picker dropdown it won't let me select anything. 

This problem seems to be iOS mobile only. It's working on mobile chrome.

**Comment by JohnDanz** [comment] 2020-02-19 19:03
I'm unable to reproduce this issue, the date picker seems to work just fine for me. Maybe this was corrected and unclosed? need more information to debug if this is still an issue.

**Comment by andrewdamelio** [comment] 2020-03-09 17:16
tested this and seems fine for me, check in both iOS Chrome / iOS Safari.

**Comment by matt-bullock** [comment] 2020-03-09 20:46
tested on ipad safari and is working. closing

**Closed as completed by matt-bullock** 2020-03-09 20:46 UTC
Labels: type/bug, prio/1, release/v2.0
