### ISSUE TITLE
[BUG] augur-node has intermittent test failures

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#862] opened 2019-01-15 22:53 UTC
### Summary
Intermittent test failures when running `yarn test`

### Steps to reproduce
1. go  to augur-node directory
1. `npm run nuke`
1. `yarn`
1. `yarn test --forceExit --detectOpenHandles` 

NOTE: Error does not happen very time

output of the error happening:

https://gist.github.com/petong/0b2bbfc14860b7556790537611f2f636

**Comment by adrake33** [comment] 2019-01-16 00:36
@epheph Can you please spend a little time tomorrow (maybe an hour or so) taking a look at these tests to see if they can be easily made to work more reliably? @petong said they are failing about 1 out of 20 times, but that when this happens it can delay builds by around an hour.

If there's not an easy fix for this, we should discuss how best to proceed, since this test framework will eventually go away.

**Comment by epheph** [comment] 2019-01-16 01:31
Sure thing, V2 or V1?

**Comment by adrake33** [comment] 2019-01-16 01:48
This was happening in v2, correct @petong?

**Comment by epheph** [comment] 2019-01-16 21:08
This seems to be a combination of three "errors". 
1.) Since the entrypoint to the test is .js and we are running with ts-node, the .ts source gets compiled on the fly. The problem is that it is after the timer for the test starts, so if you can't do the compilation AND test run in the time (5s), that test times out
2.) When a test times out, something about Knex doesn't get cleaned up for the next test run and the attempt to create a brand new db object does not work properly (throws an error)
3.) Rejecting the beforeEach in jest does NOT halt the test run (hence getting the "undefined" business in a place where it seems impossible

/cc @justinbarry  sound about right? We dealt with issue 1 some time ago but never actually fixed it

**Comment by justinbarry** [comment] 2019-01-16 21:46
@epheph I think that is a great summary. Responding to each item:
1) We switched to babel for ts compilation which did fix this but cause some other sort of heartache.
2) This seems really brittle. There must be a way to fix that.
3) see https://github.com/facebook/jest/issues/1852. I think it is related. I wonder if we can catch the rejection and throw might behave as expected.

**Closed as completed** 2019-01-16 21:54 UTC
Labels: type/bug, prio/2
