### ISSUE TITLE
Social Media Integration

### ISSUE THREAD

**Issue by martijnvanrooij** [AugurProject/augur#752] opened 2016-08-27 17:15 UTC
I would like to be able to share a market or a summary thereof, to Twitter, Facebook, Reddit, etc., together with a hyperlink to the application and some space for comments, to gain additional interest.

**Comment by joeykrug** [comment] 2016-09-05 00:25
100% agree, dupe of https://github.com/AugurProject/augur/issues/201

**Closed by joeykrug** 2016-09-05 00:25 UTC
