### ISSUE TITLE
Buying shares pending issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#182] opened 2015-09-20 23:16 UTC
Buy shares
click on markets
return to market you bought in
will no longer be pending - just 0 shares held

**Comment by tinybike** [comment] 2015-09-20 23:33
This is a Flux issue I think.  Will track it down...

**Comment by tinybike** [comment] 2015-09-21 14:11
Looks like the issue is that shares pending are just stored locally in the react component; they're never relayed back to one of the stores.

**Comment by scottzer0** [comment] 2015-09-22 17:01
Indeed, this is a duplicate of #112 and I'm currently on this unless you've started adding pending shares to the store.

**Closed** 2015-09-26 00:24 UTC
Labels: bug
