### ISSUE TITLE
Discuss Feature Requirements for v2

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#202] opened 2018-11-29 23:37 UTC
##### General V2 Support

 - Add ability to specify version on connect
 - Segregate addresses / abi by version
 - Some APIs can/should fail with a "not supported" error if the wrong version is being used

##### General V2 Support

 - Add ability to specify version on startup
 - Maintain a unique DB per contract version / network
 - Make version globally available and use to do branching for DB structure and log handling if not backward compatible

##### V2 Logging Support

 - Process new log information and store as appropriate

##### DAI

 - Adding a denomination to all processing that currently assumes ETH
 - Adding denomination information for all getters

##### Auction

 - Depends on UI requirements as needed.

##### General V2 Support

 - Add ability to specify version of contracts like with endpoints
 - UI dynamically makes display decisions based on version of contracts as appropriate

##### DAI

 - Add ability to specify denomination in market creation
 - Add trading support
 - Add P/L display support for multiple denominations

##### REP Auction

 - Add UI for purchasing / selling REP during the auction

##### Dispute Changes

 - Support rounds that occur with no tie to fee windows then become spaced via fee windows after a threshold

##### Use or Lose Support

 - No more 5% forking bonus
 - Migrating markets requires REP and if the market is expired requires an initial report
 - Migration is disallowed past the forking period

##### Misc Changes

 - Display error/warning for market end time past the limit

##### General V2 Support

 - Specify version along with endpoints. Newest by default.

**Comment by adrake33** [comment] 2018-12-01 00:09
Dupe of #279

**Closed as completed by adrake33** 2018-12-01 00:09 UTC
Labels: type/chore, prio/1
