### ISSUE TITLE
User cannot claim proceeds (Claim button not clickable)

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#1710] opened 2019-04-17 20:21 UTC
From email:

> I’m experiencing a very odd issue while trying to claim proceeds on a market. The market has resolved, 
 the UI shows that I have outstanding returns, and it also says “Proceeds Available April 13, 2019 10:43 PM (UTC -4)” which was several days ago, but the "Claim Proceeds" button is not functional. That button is grey and can’t be clicked on.
>
> The market is the following:https://cloudflare-ipfs.com/ipfs/QmZ6kwTnc3G6mx5Jxuu8fRZZvrzwhq3yPXndnmwxqkQyrj/?ethereum_node_http=https%3a%2f%2feth-mainnet.alchemyapi.io%2fjsonrpc%2f7sE1TzCIRIQA3NJPD5wg7YRiVjhxuWAE&augur_node=wss%3a%2f%2faugur-node.augur.casino#!/market?id=0xc9f0006902b67a7a8ef0e94f9140493243bd3019

Followed by:

> Hey all, 
>
> I was able to solve the (immediate) problem I emailed you about last week, so no rush in responding, but I think I’ve stumbled on the root issue, which may still be a bug. I think the essential problem is that sometimes the “clock” in the app seems to get stuck, and can’t be reset by simply quitting and relaunching the app.
>
> You might remember that a while back I emailed about a similar issue, saying the dispute window “clock" wasn’t moving forward, and somehow I resolved that issue by a combination of restarting computer, restarting router, etc. I think this most recent problem was essentially the same problem. I say this because I was continuing to browse around the app and I noticed the dispute window “clock” was stuck again (it said the dispute window closed in something like three days, which is obviously wrong). That made me think the problem I was having claiming proceeds is tied to the problem with the dispute window “clock” which I previously emailed you about.
>
> So I went ahead and restarted my computer, my router, and tried again. When I opened up the app this time, I could click the Claim Proceeds button and the dispute window “clock” was providing an accurate countdown again.

and then

> Doing some more digging, I think I found someone who might have experienced an issue similar to mine (though a long time ago), passing along in case helpful:
> 
> https://www.reddit.com/r/Augur/comments/99nmme/unable_to_claim_proceeds_of_resolved_market/

This could be an issue with Augur Node not properly calculating the dispute window, or the UI not getting the event that tells it that the dispute window has opened, or something else in that general area.

Thoughts?

**Comment by bthaile** [comment] 2019-04-22 20:03
@pgebheim this will be addressed with 1.13, not specific code is needed. What do you want to do with this tix?

**Comment by pgebheim** [comment] 2019-04-26 17:48
@Chwy5 @bthaile -- I think this moves to 1.14

**Comment by Chwy5** [comment] 2019-04-27 11:30
I have never seen this work incorrectly....I am wondering if it was in the 3 day waiting period and they didnt see the countdown clock....either way we should remove the claim button if it is within that time period....we can investigate further in 1.14

**Comment by pgebheim** [comment] 2019-04-27 14:18
Agreed. I actually think the user was having something flakey with the AN subscriptions and didn't get the notification that the market state had changed.

Seems it was fixed by a restart which would indicate something like that.

Paul
paul@augur.net

________________________________

**Comment by andrewdamelio** [comment] 2019-07-24 14:42
closing - can't reproduce, looks like a v1 error regardless

**Closed as completed by andrewdamelio** 2019-07-24 14:42 UTC
Labels: type/bug
