### ISSUE TITLE
Design QA - Unsigned orders Modal bug

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9379] opened 2020-10-04 18:40 UTC
@Chwy5  this seems a bug to me, but I don't understand what is happening. The explanation, and the video, which is more clear:

Use case:
- I individually signed the orders.
- They were processed
- The button "Submit all" was still available (Which I think shouldn't be because I've already signed the orders)
- I clicked several times "Submit all" and seems to sign the orders again every time. 
- I closed the modal, and the notification was still on the Notifs Box. 

![sign-orders](https://user-images.githubusercontent.com/49915900/95024189-e80cb380-0657-11eb-9eca-d3ce96ad6aaf.gif)

**Comment by Chwy5** [comment] 2020-10-05 12:28
Looks like the submit all button needs to be disabled when you hit the second "Submit" button

**Comment by Chwy5** [comment] 2020-10-06 14:04
The Submit all does gray out and show processing when I sign the txs, but after completing it goes back to saying submit all instead of like a checkmark or confirmed

**Comment by phoebemirman** [comment] 2020-10-12 19:30
closing.  dupe of https://github.com/AugurProject/augur/issues/9405

**Closed as completed by phoebemirman** 2020-10-12 19:30 UTC
Labels: type/bug, prio/1, project/betting, project/sportsbook
