### ISSUE TITLE
Ballot without reputation

### ISSUE THREAD

**Issue by evand** [AugurProject/augur#114] opened 2015-07-12 18:52 UTC
I'm being asked to submit a ballot even though I have zero reputation; this is nonsensical. It's possibly useful / informative to show what the ballot is even though I can't submit one, but if so then it should be abundantly clear to the user that this is the case, and that submitting a ballot is not required and won't do anything (or is impossible, whatever the case is).

**Comment by Frankenmint** [comment] 2015-10-05 10:05
So far I can’t reproduce it.  Confirmed that hosted geth works seamlessly with node js instead of pulling from hosted - BUT mongodb hosted runs great.  I had to removed db and resync to see where things are at.  Takes FOREVER to get the IPC rolling - i spend maybe 25 minutes then magically my machine whirls to life.   I started by running the localhost code then tried the client.augur < which is out of date << is divshot the equivalent of staging/beta testing and Client is the stable well tested version?

**Comment by tinybike** [comment] 2015-10-06 19:06
If you're making requests to geth directly from the browser, you're using RPC instead of IPC.  (IPC unfortunately doesn't work from the browser.)  It's definitely true that even localhost RPC is too slow at this point, and will only get worse as the number of markets grows.  Trying to solve this problem in 2 ways: 1) using a decentralized cache instead of MongoDB (#198), and 2) using a small server-side process that could use IPC to communicate with geth (#194).

**Comment by tinybike** [comment] 2015-12-26 12:43
Unable to reproduce this; closing for now.

**Closed by tinybike** 2015-12-26 12:43 UTC
Labels: bug

**Comment by housemobile** [comment] 2016-04-04 14:07
I also have 0 rep but have a ton of ballots to report
