### ISSUE TITLE
trading page scroll is weird on safari/actual devices

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1912] opened 2019-04-26 00:23 UTC
![image](https://user-images.githubusercontent.com/6775839/56776008-c169fe00-677e-11e9-9e71-b18a60a218f0.png)

looks to be a safari bug, so it shows up with coinbase wallet on iOS.

**Comment by phoebemirman** [comment] 2019-04-26 00:27
@Chwy5

**Comment by Chwy5** [comment] 2019-04-26 12:20
approved

**Comment by Chwy5** [comment] 2019-04-26 13:59
looks to be safari specific

**Comment by JohnDanz** [comment] 2019-04-26 14:28
So this looks to be caused by that Google Translate Bar -- when i dismiss it then it pops to the right spot. Not positive how we can fix this because the bar is pushing the content of the page down, which pushes the whole yes thing down -- I'll see if i can find a way to reposition the outcome thing to not move

**Comment by Chwy5** [comment] 2019-04-26 16:43
closing

**Closed as completed by Chwy5** 2019-04-26 16:43 UTC
Labels: type/bug, prio/0
