### ISSUE TITLE
Ledger not working in FireFox

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#189] opened 2018-11-29 23:37 UTC
Ledger needs SSL to work FireFox has some issues with the way we are either using self signed certificates or that we use ws://  to connect to augur-node, maybe they want wss://

Need to get ledger working in Chrome first.

**Comment by adrake33** [comment] 2018-12-01 00:42
Dupe of #262

**Closed as completed by adrake33** 2018-12-01 00:42 UTC
Labels: type/bug, prio/2
