### ISSUE TITLE
(possible dupe?) allow market creation to specify exact time a market will close for trading

### ISSUE THREAD

**Issue by RonB7139** [AugurProject/augur#450] opened 2016-03-12 21:48 UTC
for example, allow a market to be created that can be specified to be closed at a specific time (hours:minutes) for trading i.e. 1 minute before the beginning of a sporting event

**Comment by tinybike** [comment] 2016-03-14 11:45
Duplicate of #200.

**Closed by tinybike** 2016-03-14 11:45 UTC
Labels: duplicate
