### ISSUE TITLE
Processing button feedback for reporting and disputing pages

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6462] opened 2020-02-26 15:16 UTC
Processing button state design: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=8223%3A4544

Needed in these places

Get Participation Tokens and Redeem Past Participation Tokens

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c31e4571-3f1c-4036-a109-5158ea80fb9b)

---

Update button in Designated and Open reporting - remove dot dot dot and add spinner to be consistent across all processing buttons

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/908e297c-622a-42c9-b0a4-02c94aaa0968)

---

Report button on market page

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/07f5f23d-0f86-4413-a9fd-1c654387edec)

---

Dispute/support button on market page

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/dd1a3184-ab6e-4e88-836b-19859673ea2d)

---

See this ticket for dispute cards https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/6461

**Comment by phoebemirman** [comment] 2020-02-26 20:41
closing - dupe of https://github.com/AugurProject/augur/issues/6469

**Closed as completed by phoebemirman** 2020-02-26 20:41 UTC
Labels: prio/2, release/v2.0
