### ISSUE TITLE
Redeem stake and fees modal claim all

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1661] opened 2019-04-12 20:54 UTC
Add the functionality where if user clicks "claim proceeds" for one market then clicks "claim all" it removes that market from the list of what they are claiming for claim all

**Comment by Chwy5** [comment] 2019-04-13 12:51
Approved

**Comment by Chwy5** [comment] 2019-04-13 14:55
Closing - duplicate of 1623

**Closed as completed by Chwy5** 2019-04-13 14:55 UTC
Labels: type/feature, prio/1
