### ISSUE TITLE
Order Created on the order book also showed up in unassigned pending orders for initial liquidity

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#366] opened 2018-12-04 04:10 UTC
@johndanz @tomhaile 
I created a categorical 5 market...which I provided 33 orders in pre-liquidity.  I signed the MM pop up for the new market creation and then signed the MM pop-up for the first order.  The order hit up on the order book (i have a tx hash confirmation on the tx pg as well as a confirmation in MM).  There was not a notification (in the bell) for my order.
There was also not any more MM popups...My other 32 initial liquidity orders show under My Markets pg (with the yellow message to submit or cancel these orders)
The BIG issue is that my first order, which hit up on the order book is also listed (the top one in the screenshot) under the initial liquidity orders which still need to be submitted
...

I can't reproduce this issue. @tomhaile have you been able to reproduce this since yesterday when @chwy reported it? I've tried 3 times this morning on master everything, cat 5 markets, at least 33 orders each time.

I'm seeing the expected behavior of market creation tx confirming > sign first order > sign 2nd order > etc. There is no delay or wait for the orders to be "confirmed" before you are prompted to sign the next one.
 -JohnDanz
...

I wasn't able to repro, tried on rinkeby.
 -bthaile

**Comment by JohnDanz** [comment] 2018-12-13 15:36
@Chwy5 have you seen this happening at all? if not I'm going to close it as tom and I couldn't reproduce this behavior.

**Comment by Chwy5** [comment] 2018-12-13 17:09
I have not seen it occur again
@adrake33 Do w have a place to hold un-reproducible bugs, instead of closing, so if an event does happen again we can go back and look at a past ticket?

**Comment by adrake33** [comment] 2018-12-13 17:16
I've been labeling them as unreproducible bugs. We can go ahead and close them at this point. (I don't think we've seen any of the open ones for a while.).  They will still be searchable on the issues page like "is:issue is:closed <search terms>". You can also view all of them with "is:issue label:unreproducible". We can reopen them as need be.

**Closed as completed by adrake33** 2018-12-13 17:16 UTC
Labels: type/bug, prio/0, status/unreproducible
