### ISSUE TITLE
Launch Augur by clicking a link with custom url params

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#446] opened 2018-12-04 04:20 UTC
APL is talking with exchanges about an affiliate program where they promote APL markets in exchange for a percentage of the trading fees genrated for users they refer.

At a very high level, 
1)User clicks referral link, gets sent to a landing page APL controls 2)Landing page creates account for user, records account as referred.
3)Landing page generates a link that will launch the UI, prompt them for their password, then dump them into the trading page for the market of the link the clicked on.

So the link they would click on to launch Augur would look something like:
ipfs.io/augur?account=long_accont_string&market_redirect=marketId&market_filters=marketId1,marketId2,marketId3

Params:
-account is the encoded string they will immediately be prompted to log into
-market_redirect is where they will be redirected after login
-market_filters is a list of marketIDs that are part of this particular affiliate program. This will set a filter on the UI so it's only displaying these markets (which they can turn off if they want to see all markets).

@tinybike can you comment on how feasible this would be?
...

Sounds feasible.  You'd want the APL landing page to plug directly into augur.js to create account etc.  Only thing you'd have to add to augur.js/augur-core is something to mark the account as referred, AFAIK there isn't anything that could be used for that at the moment.  (Unless you're wanting to store that in a proprietary APL DB?  In which case, no problem.)

Adding that to the register record on chain would be simple tho -- here's the register contract: https://github.com/AugurProject/augur-core/blob/master/src/data_api/register.se -- could easily add an extra `referrer` field to the `registration` event that had the ethereum address of a referring account.  So that'd be the address of the exchange in this case.

...

My plan for now is just for APL to maintain our own centralized db of accounts we referred. Adding this on chain adds a bit of transparency I guess, but affiliates still have to trust that we are adding this correctly and honestly. Ultimately it's probably not worth adding the extra storage expense to keep this on chain.

...

Update on this: Ron is waiting to hear back from Kraken to solidify the deal, and to detail what user parameters would be needed for this.
 -tomkysar
...

@sprinkle Is this still relevant or should it be archived?
 -sharkcrayon
...

Only item that is not currently directly possible is the `account` item.  We’ve done away with local accounts, so this would no longer be possible.  What we _could_ do however is have the UI check that the account they’re logging in w/ from some auth method (MM, Ledger, etc.) matches the address passed.  

The other two params are doable as well, just not currently implemented.

Overall, doable, we’d just need to sync on the UX.

Definitely not MVP, but something to discuss for post release.

...

@achapman @k_day Is this still something to pursue? 
 -bthaile
...

This is no longer relevant. Can be archived.
 -nuevoalex
...

May become relevant with APL2.
 -adrake33
...

Really this is basically just:

1) in addition to the market parameter to load a market when loading the UI, also have a list of markets which are all that is shown in the UI be another query param to the URL. Or alternatively,  params which are market creator addresses which filters markets in the UI by those addresses
 -joeykrug

**Comment by joeykrug** [comment] 2018-12-22 22:55
Basically a duplicate of #486

**Closed as completed by joeykrug** 2018-12-22 22:55 UTC
Labels: type/feature, prio/3
