### ISSUE TITLE
Firefox: "Too much recursion"

### ISSUE THREAD

**Issue by evand** [AugurProject/augur#98] opened 2015-07-06 03:52 UTC
On the Javascript console in Firefox (Iceweasel 38.1.0) I get a vast number of "too much recursion" messages.

too much recursion app.js:107336:19
too much recursion app.js:103781:12
too much recursion app.js:56096:10

etc.

**Comment by tinybike** [comment] 2015-07-06 04:27
I can confirm I get these error messages as well in Firefox ("for Ubuntu") 38.0.  Seems to really slow the browser down, too.

**Comment by scottzer0** [comment] 2015-07-06 05:18
have you checked to see if your computer is plugged in? easy mistake.

**Comment by tinybike** [comment] 2015-07-09 23:26
I'm no longer getting this message as of 5156dc809ff101f581da696e12f51e6cf26c2f9c.  Closing this for now; if this pops up again for anyone else, please re-open this issue.

**Comment by evand** [comment] 2015-07-10 20:18
Did a very brief check, no longer getting errors here either.

**Comment by tinybike** [comment] 2015-07-13 13:45
This issue has reared its ugly head again, I'm sad to report:
```
too much recursion
var result = request.responseText; app.js (line 110296, col 8)

too much recursion	
m._isValid = !isNaN(m._d.getTime()) &&
app.js (line 21601, col 26)

too much recursion	
if (isCustomAttributeFn(attributeName)) {
```
Only seems to happen in Firefox, as before.

**Comment by scottzer0** [comment] 2015-07-17 20:55
i'm guessing this sometimes happens (depending on network/cpu) due to the vast number of async operations happening on load to get all the markets and subsequent data.   although, i wouldn't call it very recursive.  in fact, the market fetching has been flattened somewhat and i would say only goes about 3 deep per market (one async call, making another, then possibly another.

so, i'm not exactly sure.

**Comment by scottzer0** [comment] 2015-08-30 00:24
it could also have been relating to the unoptimized react rendering.  i'm not getting this anymore after test firefox mac os and windows with both remote and local (local lan) geth instance.   

going to close for now.

**Closed by scottzer0** 2015-08-30 00:24 UTC
Labels: bug
