### ISSUE TITLE
UI slow when loading things like new dispute markets with new dispute windows

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#794] opened 2019-01-05 22:21 UTC
" I have similar issues w/ slow UI refresh too. I think the bottleneck might be in the client between node pickups the new block(s) and feeds to the localhost http server.  There are few seconds lags at minimum. To process a large amount of data (like swtich from previous fee window to current one) and display in Chrome browser, it could take up to 1 minute sometimes on a high resolution monitor (4K) and slow GPU/CPU."

"On wednesday when the window rolled over my cpu was pegged at 100% for 10 minutes processing augur stuff"

**Comment by adrake33** [comment] 2019-01-07 16:59
This is a dupe of https://github.com/AugurProject/augur/issues/779 and has been fixed by @bthaile's PR: https://github.com/AugurProject/augur-ui/pull/2589

**Closed as completed by adrake33** 2019-01-07 16:59 UTC
