### ISSUE TITLE
Review App for Major Design Issues

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#199] opened 2018-11-29 23:37 UTC
Matt will be the owner here after he's added to CH.

Explore the app. The purpose here is to get to know it, and to keep an eye out for glaring visual and usability issues. This is a first pass for the major issues that jump out at you; we can do a more fine-toothed pass later on.

Keep a list of the issues you find.  Separate them by priority: having a "high priority" and "low priority" list is probably enough granularity here, but do what you think is right.

**Comment by adrake33** [comment] 2018-12-01 00:30
Dupe of #275

**Closed as completed by adrake33** 2018-12-01 00:30 UTC
Labels: type/chore
