### ISSUE TITLE
Fake initial reporting tx Fail -bug

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7823] opened 2020-05-20 15:36 UTC
I was in the open reporting section of reporting....reported No on a yes/no market....box showed failed
Console showed failed and then it went through....see screenshot

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/c14454bd-f3d6-4267-885e-d2dd6fc74798)

**Comment by bthaile** [comment] 2020-05-26 19:52
Not able to reproduce this issue. moving to needs feedback, we need to keep an eye out for this issue.

**Comment by nuevoalex** [comment] 2020-07-17 17:30
This appears to be a metamask/infura issue that we can't directly address in a great way as the response from Infura itself in null which means for all we know the transaction did in fact fail. Evidently its been an open issue for MM for some time:

https://github.com/MetaMask/metamask-extension/issues/6750

If it becomes a serious reoccurring problem we should think of ways to mitigate it, otherwise I opt we punt on doing anything.

**Closed as completed** 2021-03-01 19:16 UTC
Labels: type/bug, prio/1, release/v2.0, status/investigating
