### ISSUE TITLE
Account creation issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#256] opened 2016-01-18 18:07 UTC
On https://augur-dev.firebaseapp.com
Created a new account - joeykrug447
Checked remember me
Have 1337 eth
Refreshed - now have 0 ether down from 1337
Refresh a few more times, have 1336.99
Then ether updates to 0
Refresh again - still 0
Refresh again... still 0

The whole time both cash and rep were 0

**Comment by joeykrug** [comment] 2016-01-18 18:11
Signout, sign back in, still all 0

**Comment by tinybike** [comment] 2016-01-26 00:51
I haven't been able to reproduce this issue, but I think the problem was that one of the nodes' geth instance was out-of-sync with the others (because it hadn't been upgraded in quite a while).  Can you re-try registering on https://augur-dev.firebaseapp.com/ and see if this still happens for you?

**Comment by tinybike** [comment] 2016-01-26 06:06
Closing this for now, but please re-open if it happens again.

**Closed by tinybike** 2016-01-26 06:06 UTC
Labels: bug
