### ISSUE TITLE
Cash amount behaves strangely

### ISSUE THREAD

**Issue by tyche78** [AugurProject/augur#473] opened 2016-03-14 23:57 UTC
Not sure if bug or feature, but when I make a trade costing 5,000 cash with 10,000 in the bank, my new cash holdings are ~9,214 instead of 5,000

**Comment by tinybike** [comment] 2016-05-01 12:21
Closing b/c I'm unable to reproduce this; please re-open if this is still happening for you.

**Closed by tinybike** 2016-05-01 12:21 UTC
Labels: bug
