### ISSUE TITLE
Selling Shares Causes UI to Zero Out in Demo

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#125] opened 2015-07-15 19:45 UTC
It does seem to correct upon a refresh though.

**Comment by joeykrug** [comment] 2015-07-28 01:56
Still happens
![screen shot 2015-07-27 at 8 56 42 pm](https://cloud.githubusercontent.com/assets/5925937/8921932/04992b74-34a2-11e5-8ecc-59de573df3f6.png)

**Comment by scottzer0** [comment] 2015-08-30 00:25
duplicate of #110

**Closed** 2015-08-31 00:38 UTC
Labels: bug
