### ISSUE TITLE
Graphs for multiple choice markets make no sense

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#379] opened 2016-03-01 17:56 UTC
https://augur-dev.firebaseapp.com/markets/661ceda3595e6f97fc07d5fff29626e2ab372de9627e924297546bbb88ce59b

has yes/no..

**Comment by tinybike** [comment] 2016-03-02 21:35
Duplicate of #342.

**Closed by tinybike** 2016-03-02 21:35 UTC
Labels: bug, duplicate
