### ISSUE TITLE
Review Mobile Functionality

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#385] opened 2018-12-04 04:13 UTC
Go through the Augur UI, testing various bits of functionality and making issues in CH for design or function problems that arise:

 - Viewing / Searching Markets
 - Market Display
 - Trading
 - Universe selection
 - Viewing Reporting pages
 - Disputing
 - Viewing Portfolio Pages
 - Claiming market proceeds
 - Claiming reporting proceeds
...

 We should wait to do this until we get through a lot of the redesign. 
 -sharkcrayon

**Comment by joeykrug** [comment] 2019-03-09 20:31
dupe of mobile cleanup epic

**Closed as completed by joeykrug** 2019-03-09 20:31 UTC
Labels: type/chore, prio/2, area/design
