### ISSUE TITLE
Market Sort Options pending Backend Support

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#3480] opened 2019-09-05 18:53 UTC
Market sort options don't work for the below sort options. 
```
GetMarketsSortBy.marketOI
GetMarketsSortBy.volume
```

**Comment by adrake33** [comment] 2019-09-05 19:28
Dupe of #3023. I'll add a note to it to look into marketOI/volume sorting

**Comment by adrake33** [comment] 2019-09-05 19:31
Reopening and removing parts about liquidity sorting, since those are in #3023.

**Closed as completed** 2019-09-11 00:03 UTC
