### ISSUE TITLE
Write middleware invalid filter code (take gas price, actual arb size, calculate TVOM + total cost and filter markets where current arb doesn't cover this

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#10692] opened 2021-02-19 17:00 UTC
update add/remove estimates to include "no" and "yes" shares returned to user from Invalid balancer pool

**Comment by pgebheim** [comment] 2021-03-01 21:33
@bthaile -- This was our original tracking ticket for this -- this can be closed as soon as that work is done / ready for testing, or now if you had another ticket for tracking it.

**Comment by pgebheim** [comment] 2021-03-08 17:30
should #10694 be a duplicate of this?

**Comment by bthaile** [comment] 2021-03-08 23:48
I closed #10694 as done

**Comment by Chwy5** [comment] 2021-03-24 17:52
closing

**Closed as completed by Chwy5** 2021-03-24 17:52 UTC
Labels: est 2
