### ISSUE TITLE
No toggles back to Yes in order ticket

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#10886] opened 2021-03-17 17:43 UTC
Buy no shares on a market...click on No to sell them...and wait...no toggles back to yes

**Comment by Chwy5** [comment] 2021-03-18 12:46
Still not working

**Comment by JohnDanz** [comment] 2021-03-18 14:44
<img width="2560" alt="Screen Shot 2021-03-18 at 9 42 04 AM" src="https://user-images.githubusercontent.com/10524630/111645081-686e3d80-87ce-11eb-9ad3-b2e43a027c40.png">
<img width="2558" alt="Screen Shot 2021-03-18 at 9 43 07 AM" src="https://user-images.githubusercontent.com/10524630/111645117-6c01c480-87ce-11eb-9bcf-6e6c42f7db59.png">


I'm unable to reproduce this, this is 2 screenshots showing the time when I switched to no (top screen has a date/time printed) then ~1 min later without touching anything or leaving my browser I took another screenshot showing it still on no. Also has a date/time for clarity in screenshots.

**Comment by JohnDanz** [comment] 2021-03-18 15:15
this has been fixed, confirmed this morning with chwy. closing.

**Closed as completed by JohnDanz** 2021-03-18 15:15 UTC
Labels: type/bug, prio/1
