### ISSUE TITLE
Change global chat to Orbit

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7500] opened 2020-04-27 23:39 UTC
Torus takes 3 signings and portis takes 2 signings......This needs to get down to 1 signing

Also the speed of loading takes forever....a good 1 minute after I hit the load chat button

**Comment by pgebheim** [comment] 2020-04-28 15:25
Removing bug label because this isn't a bug, the signings are as designed by 3box and there's nothing we can really do about that approach.

As for speed, the probably solution is to try to load it a little earlier so that the ipfs connections can be all warmed up. Ideally this would be an optimization that we do at some point that shares the same ipfs instance between 3box and the warp sync client.

@bconfortin Can you add your notes here?

**Comment by bconfortin** [comment] 2020-04-28 16:12
@pgebheim 
We might be able to solve the number of signings. 3box released something they are calling 3ID Connect and it should become the only way to use their solutions.
<https://medium.com/3box/introducing-3id-connect-531af4f84d3f>

Perhaps the most important parts for this discussion:

> Fewer wallet signatures 🔑
3ID Connect uses an HD trie to derive database keys for 3Box spaces from the user’s 3ID, so users only need to sign one message to consent to all permissions requested by an application instead of signing one message for each individual permission.
Persistent 3Box sessions 🔁
3ID Connect allows users to persist 3Box sessions across application browser tabs, eliminating the need for users to sign into each individual tab.

I haven't yet dived into all of it and how it'll all work but this might be a concern, since I don't see Torus:
> The following providers are initially supported; MetaMask and other injected providers, Fortmatic, Authereum, Portis, and WalletConnect.

As for speed, I am not sure how that IPFS early load would work, I would have to test that. Sounds promising though.

**Comment by Chwy5** [comment] 2020-05-06 21:07
worked on desktop for me but wont load on Mobile.... @matt-bullock try it
worked the second time i tried
Yeah seems to be working for me now

**Comment by bconfortin** [comment] 2020-05-06 21:21
Are you on Android or iOS?

Em qua., 6 de mai. de 2020 às 18:07, Chwy5 <notifications@github.com>
escreveu:

**Comment by Chwy5** [comment] 2020-05-06 22:05
No chrome android...

**Comment by matt-bullock** [comment] 2020-05-07 09:32
Works for me. Closing

**Closed as completed by matt-bullock** 2020-05-07 09:32 UTC
Labels: prio/1, status/investigating, feature/comments
