### ISSUE TITLE
Add walkthrough/tutorial to the UI

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#560] opened 2018-12-04 17:29 UTC
There are a number of examples of libraries that provide this functionality.

https://introjs.com/
http://linkedin.github.io/hopscotch/
...

- "New users should be given some basic tutorial for asks/bids, what they mean and what you stand to win from betting and how to trade. Or what you stand to earn from creating."
- And ditto for reporting
 -joeykrug
...

@serena Is this something you want to design out for v2?
 -bthaile
...

Yes, and that's good timing for it. Putting this as low priority since we need to get through a deeper overhaul of the UI first.
 -sharkcrayon

**Comment by pgebheim** [comment] 2019-10-29 20:30
Duplicate of #3998

**Closed as completed by pgebheim** 2019-10-29 20:30 UTC
Labels: type/feature, prio/3, area/design, status/duplicate
