### ISSUE TITLE
Only run tests for changed modules in CI

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#196] opened 2018-11-29 23:37 UTC
This will help us conserve build resources and significantly speed up CI.
Probably involves this command:

`npx lerna ls --since $SYSTEM_PULLREQUEST_TARGETBRANCH`

Note: `$SYSTEM_PULLREQUEST_TARGETBRANCH` is provided by Azure CI pipelines.

**Comment by adrake33** [comment] 2018-12-01 00:35
Dupe of #272

**Closed as completed by adrake33** 2018-12-01 00:35 UTC
Labels: type/chore, prio/1
