### ISSUE TITLE
Github: Additional user centric sorting to dispute markets view

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#528] opened 2018-12-04 17:26 UTC
This is a nice to have and we need to discuss before doing anything. 

Have markets sort accordining to user’s interest.

1. Markets user has rep in / is a reporter in / disputed
2. Markets the user currently has shares in
3. Markets user has favorited.
4. Markets in the process of crowdsourcing rep disputes
5. Markets sorted by highest dispute round
6. Markets sorted by highest dispute bond
7. Markets by volume

https://github.com/AugurProject/augur-app/issues/213#issuecomment-406875773
...

@serena I think there are a few ch tix about sort/filtering dispute markets. Here is another one. We could just add filter sort to dispute page.
 -bthaile
...

@serena Please add a priority to this.
 -adrake33

**Comment by adrake33** [comment] 2018-12-06 01:14
Closing as duplicate of #574

**Closed as completed by adrake33** 2018-12-06 01:14 UTC
Labels: type/feature, prio/1, area/design
