### ISSUE TITLE
Unrealized PL for outcomes acquired through a short position which become a long can be wrong

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#896] opened 2019-01-25 00:38 UTC
Steps to reproduce:

 - Find/create a 3 outcome categorical market. There must be no trades on outcome C
 - Acquire a short position of outcome 0
 - Sell a _portion_ of outcome B

Observe that a long position now exists for Outcome C. This is correct, however since it has not been traded the unrealized PL should be 0. Instead the unrealized PL assumes an outcome value of 0.

When no trades have occurred for an outcome the unrealized should be 0.

**Comment by adrake33** [comment] 2019-02-04 22:12
Closing as a dupe of https://github.com/AugurProject/augur/issues/958.

**Closed as completed by adrake33** 2019-02-04 22:12 UTC
Labels: type/bug, prio/1
