### ISSUE TITLE
Design QA - Market Detail Page Stats

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9132] opened 2020-08-27 11:21 UTC
Boxes should have all the same size
Margin between them should be smaller (24px)

<img width="1227" alt="Screen Shot 2020-08-27 at 08 27 57" src="https://user-images.githubusercontent.com/49915900/91436851-4d8ea880-e83f-11ea-84fc-cc22bf60120e.png">

**Comment by yanelbottini** [comment] 2020-09-21 23:17
Looks fine on big resolutions, but it's not working fine on smaller ones:

![responsive-stats](https://user-images.githubusercontent.com/49915900/93830753-768c3880-fc47-11ea-9260-8f8a151dd998.gif)

<img width="1500" alt="Screen Shot 2020-09-21 at 20 14 29" src="https://user-images.githubusercontent.com/49915900/93830762-7db34680-fc47-11ea-9bb4-7fb154d40be6.png">

Figma reference:
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7654%3A268226

**Comment by yanelbottini** [comment] 2020-09-23 20:49
Sorry, still not looking good: Top and bottom padding should be the same in all the instances:

<img width="1060" alt="Screen Shot 2020-09-23 at 17 48 56" src="https://user-images.githubusercontent.com/49915900/94068064-16bb9c00-fdc5-11ea-9d89-a6d63d5404cf.png">

<img width="719" alt="Screen Shot 2020-09-23 at 17 49 32" src="https://user-images.githubusercontent.com/49915900/94068119-2804a880-fdc5-11ea-9d3f-40f37b98ffac.png">

**Comment by yanelbottini** [comment] 2020-09-25 20:21
It's working better, but in some cases the boxes don't have the same size:
![stats](https://user-images.githubusercontent.com/49915900/94311935-709d9c80-ff52-11ea-8d30-3d3fe7a9a857.gif)

**Comment by yanelbottini** [comment] 2020-09-30 20:12
Hi @JohnDanz. Looks good. The only thing missing is that top and bottom margins should be the same: 12px.

<img width="497" alt="Screen Shot 2020-09-30 at 17 11 27" src="https://user-images.githubusercontent.com/49915900/94734774-14ff5480-0340-11eb-8e2e-b89e7cb8807e.png">

**Comment by JohnDanz** [comment] 2020-09-30 21:35
@yanelbottini in order to achieve that, something would have to grow to keep them all the same size. The issue is the amount of text on one of them forces a 2nd line of grey text so if they all need to be the same height, i'm not sure how I can also ensure they all keep exactly 12 px padding surrounding the inner content. So for example, where would  those extra ~4 px go on the bottom? Otherwise this particular info box would be smaller than the biggest one, like illustrated in the previous comment.

**Comment by matt-bullock** [comment] 2020-10-02 11:21
let's just close this as it doesn't look too bad

**Closed as completed by matt-bullock** 2020-10-02 11:21 UTC
Labels: prio/2, project/betting, project/sportsbook
