### ISSUE TITLE
Have search search the answers as well

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#479] opened 2016-03-15 12:20 UTC
If I search for Clinton, I don't only want to see 'Will Hillary Clinton win the US Presidency'

I also want to see 'Who will win the 2016 US Election' where Hillary Clinton is one of the possible answers.

**Comment by tinybike** [comment] 2016-03-18 06:34
Duplicate of #426.

**Closed by tinybike** 2016-03-18 06:34 UTC
Labels: duplicate
