### ISSUE TITLE
Ether cost information

### ISSUE THREAD

**Issue by evand** [AugurProject/augur#126] opened 2015-07-16 02:42 UTC
Which buttons cost Ether to click? How much Ether? What does that cost in USD / BTC equivalent? Are these costs fixed or variable over time? Does it depend which button I click? Which market I click said button on? Might I want to spend more or less than the default amount, in order to get my action processed sooner / spend less money on fees?

All of these questions should be answered by the UI or documentation somewhere accessible; if the answer is "it's vanishingly small", then the answer could probably be a bit less convenient, but at least having a good estimate for how small is small would be good.

**Comment by scottzer0** [comment] 2015-08-30 17:27
duplicate of #147

**Closed by scottzer0** 2015-08-30 17:27 UTC
Labels: enhancement
