### ISSUE TITLE
Redesign Sidebar Menu

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#214] opened 2018-11-29 23:43 UTC
Ideally, we move the menu to the top bar. This also involves re-doing the category and tag filters on the market list page. 

-  consider how to order categories and tags. Possibly alphabetical or by open interest or volume. 

Revisit this story when the filters are redone: ch14840

**Comment by adrake33** [comment] 2018-11-30 23:57
Dupe of #295

**Closed as completed by adrake33** 2018-11-30 23:57 UTC
Labels: type/feature, prio/0
