### ISSUE TITLE
position doesn't load if going straight to portfolio page

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#814] opened 2019-01-09 18:07 UTC
this is on master and dev.augur.net, loaded up the position page and says i don't have a position. but then when i click on the market the position is shown. 

<img width="1183" alt="screen shot 2019-01-09 at 10 05 35 am" src="https://user-images.githubusercontent.com/6775839/50918936-5de9d980-13f6-11e9-8424-4a109b7c0087.png">
<img width="1398" alt="screen shot 2019-01-09 at 10 05 28 am" src="https://user-images.githubusercontent.com/6775839/50918937-5de9d980-13f6-11e9-8bbc-b6c41fcb5c46.png">

**Comment by pgebheim** [comment] 2019-01-09 18:48
If you then go back to the positions page, is the data there?

**Comment by phoebemirman** [comment] 2019-01-09 19:19
yea. it loads once you go to the market page

**Comment by JohnDanz** [comment] 2019-01-10 19:02
I'm unable to reproduce this, I've tried I get redirected to markets list and if i then navigate to portfolio i can see my position. If i start from reporting on a refresh, then go to portfolio i see my position. Will close this ticket by EoD unless it can be reproduced

**Closed as completed** 2019-01-10 22:28 UTC
Labels: type/bug, prio/1
