### ISSUE TITLE
Mobile: Market list page. Add a clear button next to the category header

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7510] opened 2020-04-28 18:14 UTC
If the user has filtered by a category then it should show the X (clear button) next to the category text. Tapping this will change the filter back to 'Popular Markets' and the text here will say 'Popular Markets'. No clear button needed when showing Popular Markets.

Give X button a good hit area of roughly 20x20px

[design](https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1331%3A3936)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c6dcc9de-cea6-48b8-ad7b-92913dad3c3a)

**Comment by pgebheim** [comment] 2020-04-28 18:18
I think we should push this into v2.1 -- nice to have but isn't stability/performance.

@matt-bullock @Chwy5

**Comment by Chwy5** [comment] 2020-04-28 18:22
We actually need it...I got into that state yesterday and there is no way out without getting out of the site or at least not easily found....there is no back button there

**Comment by pgebheim** [comment] 2020-04-28 18:23
What do you mean no way of getting out of the site? The user can click on "Categories and Filters" again, click "All Categories" and hit apply.

We need to be focusing on all the various stability fixes for this release, planning on UX improvements for just after v2 launch.

**Comment by Chwy5** [comment] 2020-04-28 18:28
you can get into it by not going into categories which i found out yesterday.  If You accidentally click on a tag from the market

**Comment by pgebheim** [comment] 2020-04-28 18:47
ahh... didn't realize that.

Still in terms of severity seems minor and could be pushed into after stability.

**Comment by Chwy5** [comment] 2020-04-28 18:48
yeah we can push

**Comment by bthaile** [comment] 2020-04-28 19:43
How about using this ticket to fix the back button when user clicks on category. Then user can get out and back to known screen.

confirmed that history object gets updated correctly and the back button does go to previous url correctly.  It doesn't trigger the UI to re-query to get previous market list. 

~~Adding a "X" wouldn't work, we'd still need to fix triggering previous URL loading.~~

after more investigation we could add "X", that would give us more control. We'd still need to solve the back button issue.  By solving the back button issue we don't need the "X".

**Comment by Chwy5** [comment] 2020-05-02 13:01
ok back button works....I want to add the x for post release...moving this ticket back to do later

**Comment by bthaile** [comment] 2020-05-04 21:13
@Chwy5  can you move this to RC3, post release?

**Comment by Chwy5** [comment] 2020-05-04 21:17
rc3 looks like it is pre launch stuff.....2.1 looks post

**Closed as completed** 2021-03-01 20:32 UTC
Labels: prio/1, project/trading, release/v2.1
