### ISSUE TITLE
Handle IDB Error (from Dexie) - The database connection is closing

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7405] opened 2020-04-21 15:28 UTC
Need to handle DB closing error from Dixie

![4-21dexie.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/1c2f74c8-ec11-43a4-9828-b0d0ca0e918c)

**Comment by nuevoalex** [comment] 2020-04-22 19:52
@Chwy5 Having difficulty reproducing. Some questions:

- Were multiple tabs open when this happened?
- Was there a different error that originally happened or some failure that preceded this?
- Had your machine gone into sleep mode preceding this?
- Did refreshing fix the issue?

**Comment by Chwy5** [comment] 2020-04-22 19:58
Were multiple tabs open when this happened? - Yes
Was there a different error that originally happened or some failure that preceded this? (401) portis error 
Had your machine gone into sleep mode preceding this? - No 
Did refreshing fix the issue? - Yes

**Comment by pgebheim** [comment] 2020-04-24 15:09
Looks like this isn't eminently repeatable --- lowering the priority -- thinking we need to promote this one to be the type of uncaught error that tells users to refresh.

@andrewdamelio @bthaile -- would that be relatively easy to implement? A top level error handler hook that pops open a modal and says "Something went wrong! Please refresh"

**Comment by pgebheim** [comment] 2020-04-27 15:51
There's a similar error that happens here with ZeroX browser mesh -- it gets an error saying LevelDB closed. 0x uses a leveldb that is written as a blob into indexeddb.

![image](https://user-images.githubusercontent.com/86010/80392665-4c834580-8864-11ea-884d-04628cf878d7.png)

**Comment by pgebheim** [comment] 2020-05-06 06:16
Closing until we see this particular case again as others like it have been handled via refresh.

**Closed as completed by pgebheim** 2020-05-06 06:16 UTC
Labels: type/bug, prio/1, status/unreproducible, project/trading, release/v2.0
