### ISSUE TITLE
Account ether display issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#160] opened 2015-09-14 17:48 UTC
1) make new account
2) Ether is always blank, never updates
![screen shot 2015-09-14 at 12 46 52 pm](https://cloud.githubusercontent.com/assets/5925937/9857185/b55aa174-5ade-11e5-9155-e232c4427880.png)

Seems to actually have ether in the backend though.

**Comment by scottzer0** [comment] 2015-09-15 20:37
i'm not able to reproduce this on mac os x / chrome.  

what browser platform and is the issue consistent or just occasional?

**Comment by joeykrug** [comment] 2015-09-15 20:48
OS X latest Chrome --- consistent after account creation.

in console ```augur.rpc.balance('0xd469a8a8bb848bbb1329e33fc155516d9994ed23')/1e18```
returns 100 but ether above is blank per screenshot --- am on hosted version not localhost

**Comment by scottzer0** [comment] 2015-09-16 03:04
i published some changes that might resolve or at least help resolve the issue to http://development.augur.divshot.io/

**Comment by joeykrug** [comment] 2015-09-16 03:45
it's not allowing me to register now --- says "register failed" every time :/

**Comment by tinybike** [comment] 2015-09-16 08:55
Ether display and login/register seem to be fixed in 57af1b2e92cece424557d208d842265a344b30d0 -- closing this for now, but if this problem reappears, please re-open.

**Closed by tinybike** 2015-09-16 08:55 UTC
Labels: bug

**Comment by joeykrug** [comment] 2015-09-16 10:24
registering with username ccc and password ccc says register failed

**Comment by joeykrug** [comment] 2015-09-16 10:25
i think it's not long enough, but it doesn't tell the user or anything
