### ISSUE TITLE
Create design doc for Augur State

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#497] opened 2018-12-04 04:25 UTC
Located at https://docs.google.com/document/d/1IyAGC11daIhrhkfyTaN2Khn0QOXPKsoZZbu0mtyV6HI/

**Comment by justinbarry** [comment] 2019-02-11 17:28
How does this relate to #765?

**Comment by adrake33** [comment] 2019-02-11 18:40
Closing this as a dupe of https://github.com/AugurProject/augur/issues/765. (Info from https://docs.google.com/document/d/1IyAGC11daIhrhkfyTaN2Khn0QOXPKsoZZbu0mtyV6HI will be moved to https://docs.google.com/document/d/1ug5EU_yZjF126XOZNT3xSAe4IS5E4zPTasm5M4FY7D0.)

**Closed as completed by adrake33** 2019-02-11 18:40 UTC
Labels: type/feature, prio/1
