### ISSUE TITLE
Can't connect to Augur

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#8020] opened 2020-06-11 15:43 UTC
I installed and configured Augur on a remote server , following the instuctions on the main page :+1: 

```
yarn docker:all
yarn workspace @augurproject/ui dev
```

But when I point my browser at it, I get this javascript error:

```
modal-network-connect.tsx:82 Uncaught TypeError: Cannot read property 'ethereum' of undefined
    at ModalNetworkConnect.submitForm (modal-network-connect.tsx:82)
    at onClick (modal-button.tsx:28)
    at HTMLUnknownElement.callCallback (react-dom.development.js:347)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:397)
    at invokeGuardedCallback (react-dom.development.js:454)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:468)
    at executeDispatch (react-dom.development.js:600)
    at executeDispatchesInOrder (react-dom.development.js:622)
    at executeDispatchesAndRelease (react-dom.development.js:725)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:733)
```

Why is this happening and what I am doing wrong?
![connect_error](https://user-images.githubusercontent.com/1125368/84407321-4c4ec780-abd0-11ea-9f98-c3eeb97e0016.png)

**Comment by pgebheim** [comment] 2020-06-11 16:27
This is likely your metamask being connected to a different network than localhost.

Had you configured MM for your local node?

**Comment by nuliknol** [comment] 2020-06-11 16:45
@pgebheim 
yep, the RPC is accessible remotely, and Metamask can get the balance of the dev account.
![metamask_works](https://user-images.githubusercontent.com/1125368/84415646-aeabc600-abd8-11ea-86b3-f005db2a64bf.png)

I think the problem is that the source code assumes I am connected already :



```
    // because we prioritize, lets wipe out all previous connection options but not remove things like timeout.
    const updatedEnv = {
      ...env,
      "ethereum": {
        ...env["ethereum"],
        http: "",
        ...ethNode,
      },
    };
    const endpoints = {
      ethereumNodeHTTP: updatedEnv["ethereum"]?.http,
      ethereumNodeWS: null
    };
```

But I don't have "ethereum" object in "env" object.

**Comment by nuliknol** [comment] 2020-06-11 16:50
@pgebheim 
here is the exact line number where it fails
![code_line_number](https://user-images.githubusercontent.com/1125368/84416338-ae5ffa80-abd9-11ea-8ba9-645f9ec8cd81.png)

**Comment by pgebheim** [comment] 2020-06-11 18:53
That code is totally irrelevant. You shouldn't ever get that pop up as the UI cannot connect to it's own eth node and putting in an eth node there is a no op. This is a broken holdover from when augurv1 maintained its own ethereum connection.

If you're getting that error once that dialog pops up I'm not surprised because you should never get there.

**Comment by pgebheim** [comment] 2020-06-11 18:56
@bthaile @phoebemirman 

Why do we still have this dialog / what conditions is it being shown. It shouldnt be there anymore.

**Comment by pgebheim** [comment] 2020-06-11 19:06
This dialog is shown when there's an error calling `makeClient` which is the thing that sets up the augur SDK:

```
    try {
      sdk = await augurSdk.makeClient(provider, config);
    } catch (e) {
      console.error(e);
      if (provider._network && config.networkId !== provider._network.chainId) {
        const { setModal } = AppStatus.actions;
        return setModal({
            type: MODAL_NETWORK_MISMATCH,
            expectedNetwork: NETWORK_NAMES[Number(config.networkId)],
          });
      } else {
        return callback('SDK could not be created', { config });
      }
    }
```

The dialog itself is useless and should be change to something that shows a real error message, but the point is that there's a network mismatch -- e.g. the UI is built assuming its connected to a network with a different number than the Provider is returning.

Put a breakpoint there and see what those values are.

**Comment by bthaile** [comment] 2020-06-11 19:09
The network mismatch is only for meta mask. 

other wallet providers aren't network dependent. looks like if an error occurs we are assume the user is using meta mask and is on the wrong network.

**Comment by pgebheim** [comment] 2020-06-11 19:12
Wait I'm wrong

https://github.com/AugurProject/augur/blob/master/packages/augur-ui/src/modules/app/components/app.tsx#L174-L192

Here is where its triggered. so `initAugur` failed for some reason and we show a useless modal  -- thanks @andrewdamelio for finding this.

**Comment by pgebheim** [comment] 2020-06-11 19:13
@nuliknol -- you can stick a breakpoint in that callback and inspect err to see what's happening.

**Comment by bthaile** [comment] 2020-06-11 19:14
I think the issue is we are passing around config and it's not making it to the modal so it's undefined and ethereum http can't be found. I'll debug

I get this
![image](https://user-images.githubusercontent.com/3970376/84429644-233d2f80-abee-11ea-9e1a-5d2efa4e7ee1.png)

I'll test on local env.

**Comment by pgebheim** [comment] 2020-06-11 19:26
Oh I bet he doesnt have a local.json config....

On my branch I change how all that works.

**Comment by bthaile** [comment] 2020-06-11 19:41
I'm able to repro

![image](https://user-images.githubusercontent.com/3970376/84431894-ae6bf480-abf1-11ea-8d76-7542f80d302e.png)

there are prob a few issues. 
1. need to put the query param to connect to correct ethereum node
2. we need to fix the network connect for. 
3. I don't think we have a local.json checked into code, could use packages/augur-artifacts/src/environments/test.json

**Comment by bthaile** [comment] 2020-06-11 19:52
@pgebheim 
<https://github.com/AugurProject/augur/pull/8025/files> PR
only fixes the exception, actual fix would be:

1. update `augur/packages/augur-artifacts/src/environments/test.json` to have the correct ethereum http and ws endpoints. 

2. add `ethereum_node_http` query parameter to url with encoded http location.

**Comment by pgebheim** [comment] 2020-07-09 20:00
Endpoint configs have been changed since this ticket.

**Closed as completed by pgebheim** 2020-07-09 20:00 UTC
